kind: Template
apiVersion: v1
template: spark
metadata:
  name: spark
labels:
  app: sparkcluster
objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: ${MASTER_NAME}
    labels:
      name: ${MASTER_NAME}
  spec:
    ports:
      - protocol: TCP
        port: 7077
        targetPort: 7077
    selector:
      name: ${MASTER_NAME}

- kind: Service
  apiVersion: v1
  metadata:
    name: ${MASTER_NAME}-webui
    labels:
      name: ${MASTER_NAME}
  spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      name: ${MASTER_NAME}

- kind: Service
  apiVersion: v1
  metadata:
    name: ${ZEPPELIN_NAME}
    labels:
      name: ${MASTER_NAME}
  spec:
    ports:
      - port: 80
        targetPort: 8080
    selector:
      name: ${ZEPPELIN_NAME}
    type: LoadBalancer

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${MASTER_NAME}
    labels:
      cluster: ${CLUSTER_NAME}
      type: master
      spark-jvm-metrics: ${ENABLE_METRICS}
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      name: ${MASTER_NAME}
    template:
      metadata:
        labels:
          name: ${MASTER_NAME}
      spec:
        containers:
          - name: ${MASTER_NAME}
            image: ${SPARK_IMAGE}
            imagePullPolicy: "Always"
            env:
              - name: SPARK_MASTER_PORT
                value: "7077"
              - name: SPARK_MASTER_WEBUI_PORT
                value: "8080"
              - name: SPARK_METRICS_ON
                value: ${ENABLE_METRICS}
            ports:
              - containerPort: 7077
                protocol: TCP
              - containerPort: 8080
                protocol: TCP

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${WORKER_NAME}
    labels:
      cluster: ${CLUSTER_NAME}
      type: worker
      spark-jvm-metrics: ${ENABLE_METRICS}
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: ${WORKER_RELICAS}
    selector:
      name: ${WORKER_NAME}
    template:
      metadata:
        labels:
          name: ${WORKER_NAME}
      spec:
        containers:
          - name: ${WORKER_NAME}
            image: ${SPARK_IMAGE}
            imagePullPolicy: "Always"
            env:
              - name: SPARK_MASTER_ADDRESS
                value: spark://${MASTER_NAME}:7077
              - name: SPARK_MASTER_UI_ADDRESS
                value: http://${MASTER_NAME}-webui:8080
              - name: SPARK_METRICS_ON
                value: ${ENABLE_METRICS}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${ZEPPELIN_NAME}
    labels:
      cluster: ${CLUSTER_NAME}
      type: worker
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      name: ${ZEPPELIN_NAME}
    template:
      metadata:
        labels:
          name: ${ZEPPELIN_NAME}
      spec:
        containers:
          - name: ${ZEPPELIN_NAME}
            image: ${ZEPPELIN_IMAGE}
            imagePullPolicy: "Always"
            ports:
              - containerPort: 8080
            env:
              - name: MASTER
                value: spark://${MASTER_NAME}:7077
              - name: SPARK_MASTER_ADDRESS
                value: spark://${MASTER_NAME}:7077
              - name: SPARK_METRICS_ON
                value: ${ENABLE_METRICS}
parameters:
- name: SPARK_IMAGE
  description: Name of the Spark master/worker image
  value: docker.io/jeffreymanning/spark-base:latest
- name: ENABLE_METRICS
  description: turn on(T)/off - jvm metrics jolokia
  value: "true"
- name: CLUSTER_NAME
  description: name of cluster - applicable to spark infrastructure
  generate: expression
  from: "cluster-[a-z0-9]{4}"
  required: true
- name: MASTER_NAME
  description: master name used as a service name and a selector
  generate: expression
  from: "spark-master-[a-z0-9]{4}"
  required: true
- name: WORKER_NAME
  description: worker name used as a selector
  generate: expression
  from: "spark-worker-[a-z0-9]{4}"
  required: true
- name: WORKER_RELICAS
  description: worker replica count
  value: "3"
  required: true
- name: ZEPPELIN_NAME
  description: zeppelin name used for selector - combines with master name
  generate: expression
  from: "zeppelin-[a-z0-9]{4}"
  required: true
- name: ZEPPELIN_IMAGE
  description: Name of the Zeppelin interface
  value: docker.io/jeffreymanning/zeppelin:latest
