#!/bin/bash

# spark likes to be able to lookup a username for the running UID, if
# no name is present fake it.

# move over the existing /etc/passwd into our temp
cat /etc/passwd > ${NSS_WRAPPER_PASSWD}
echo "$(id -u):x:$(id -u):$(id -g):dynamic uid:$SPARK_HOME:/bin/false" >> ${NSS_WRAPPER_PASSWD}

export LD_PRELOAD=libnss_wrapper.so

exec "$@"
